#!/usr/bin/env node
// @ts-check

/**
 * The lexical conformance corpus: what each language's **mask** and each
 * language's **declaration shapes** must answer.
 *
 * `test/vectors/section-vectors.json` pins *resolution* — which text a
 * `#<reference>` selects. It can only do that through the handful of fixtures it
 * names, so it exercises six of the eighteen lexer entries, and it says nothing
 * at all about the shape layer in isolation: a port whose `declarations()` reads
 * `publisher: String,` as the field `lisher` can still resolve every vector,
 * because no fixture contains that line.
 *
 * This corpus closes both holes. Every case is generated by running this
 * repository's own implementation:
 *
 *   - `masks`  — one row per lexer entry (plus the built-in default engine),
 *                carrying a source that exercises every construct the entry
 *                exists for, and the mask the implementation produces. The mask
 *                keeps the length and every newline offset, which is what makes
 *                `}` inside a comment or a string harmless.
 *   - `shapes` — one row per spelling a language adds to the generic `name(`
 *                heuristics, carrying the *masked* line and the declarations the
 *                implementation reports for it: kind, name, `headerFrom` (the
 *                offset the body starts at) and the body rules. These are the
 *                rows a mistranslated matcher fails, and they are deliberately
 *                chosen to discriminate — `impl<T>` against `impl`, `pub name`
 *                against `publisher`, an indented Haskell binding against a
 *                column-0 one.
 *
 *   node tools/lexical-vectors.mjs           write/update the vectors file
 *   node tools/lexical-vectors.mjs --check   compare; exit 1 and diff on drift
 *
 * `--check` is a build gate, and `test.mjs` also holds the file to a *live*
 * call, so the corpus cannot drift from the implementation it describes.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { masked as defaultMask } from '../lib/section.mjs';
import { lexerFor } from '../src/js/scanner/lexers.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'test', 'vectors', 'lexical-vectors.json');

// ---------------------------------------------------------------------------
// The mask cases: one per lexer entry, plus the default engine.
//
// `path` selects the lexer by extension, exactly as `index.mjs` does; a null
// path is the unknown type that falls back to the built-in engine.
// ---------------------------------------------------------------------------

/** A non-ASCII identifier character (U+0141) — the boundary tests need one. */
const L = '\u0141';
/** An astral-plane character, which is two UTF-16 code units (U+1F600). */
const EMOJI = '\u{1F600}';

const maskCases = [
    { name: 'js-template-literal', path: 'a.js', source: 'const a = `x } ${y} z`;\n// c\n/* d */\n' },
    { name: 'js-comment-and-regex', path: 'a.mjs', source: '// } brace\nconst r = /[}]/;\n' },
    { name: 'ts-annotated', path: 'a.ts', source: 'const a: string = `} ${x}`;\n' },
    { name: 'tsx-annotated', path: 'a.tsx', source: 'export const A = ({ x }: P) => <div>{x}</div>;\n' },
    { name: 'java-text-block', path: 'a.java', source: 'String s = """\n  } brace\n  """;\nchar c = \'}\';\n// }\n' },
    { name: 'java-char-and-comment', path: 'a.java', source: "char q = '\\'';\n/* } */\n" },
    { name: 'zig-nested-comment', path: 'a.zig', source: '/* outer /* inner */ still */\npub fn f() void {}\n' },
    { name: 'zig-multiline-string', path: 'a.zig', source: 'const s =\n    \\\\a } brace\n;\n"q }"\n' },
    { name: 'go-raw-string', path: 'a.go', source: 's := `a } brace`\nt := "b } brace"\n' },
    { name: 'go-char-literal', path: 'a.go', source: "c := '}'\nd := '\\\\'\n" },
    { name: 'go-char-with-line-break', path: 'a.go', source: "c := '\\\n'\n" },
    { name: 'go-escaped-quote', path: 'a.go', source: 's := "a \\" } b"\n' },
    { name: 'rust-raw-string', path: 'a.rs', source: 'let s = r#"a } brace"#;\nlet t = "b }";\n' },
    { name: 'rust-lifetime-versus-char', path: 'a.rs', source: "fn f<'a>(x: &'static str) -> char { 'x' }\n" },
    { name: 'rust-nested-comment', path: 'a.rs', source: '/* outer /* inner */ fn decoy() {} */\nfn target() {}\n' },
    { name: 'rust-byte-char-with-line-break', path: 'a.rs', source: "let c = b'\\\n';\n" },
    { name: 'python-triple-quoted', path: 'a.py', source: 'x = """a } brace"""\ny = \'\'\'b }\'\'\'\n' },
    { name: 'python-raw-string', path: 'a.py', source: 'x = r"a \\" } b"\ny = r\'c }\'\n' },
    { name: 'python-raw-prefix-after-word', path: 'a.py', source: `${L}r"x"\n` },
    { name: 'python-fstring', path: 'a.py', source: 'x = f"{a} } {b}"\n' },
    { name: 'csharp-verbatim', path: 'a.cs', source: 'var s = @"a "" } b";\n' },
    { name: 'csharp-interpolated-verbatim', path: 'a.cs', source: 'var s = $@"a {b} "" } c";\n' },
    { name: 'csharp-raw-string', path: 'a.cs', source: 'var s = """a } b""";\n' },
    { name: 'kotlin-nested-comment', path: 'a.kt', source: '/* a /* b */ } */\nval s = """c } d"""\n' },
    { name: 'kotlin-char', path: 'a.kt', source: "val c = '}'\n// }\n" },
    { name: 'php-heredoc', path: 'a.php', source: '<?php\n$sql = <<<EOT\n  } brace\nEOT;\n# a comment }\n' },
    { name: 'php-attribute-is-not-a-comment', path: 'a.php', source: "#[Attribute]\nclass Cart {}\n" },
    { name: 'ruby-end-block-comment', path: 'a.rb', source: '=begin\na } brace\n=end\n# c\ndef add(x)\n  x\nend\n' },
    { name: 'ruby-heredoc-versus-shift', path: 'a.rb', source: 'items = array << x\nbody = <<~TAG\n  } brace\nTAG\n' },
    { name: 'sql-dollar-quoting', path: 'a.sql', source: 'SELECT $$a } b$$;\n-- } c\n' },
    { name: 'sql-doubled-quote', path: 'a.sql', source: "SELECT 'it''s a } brace';\n" },
    { name: 'shell-heredoc', path: 'a.sh', source: 'cat <<EOF\n  } brace\nEOF\necho \'no } escape\'\n' },
    { name: 'shell-heredoc-non-ascii-tag', path: 'a.sh', source: `cat <<${L}x\n  body\n` },
    { name: 'vb-doubling', path: 'a.vb', source: "Dim s As String = \"a \"\"; } b\"\n' c }\n" },
    { name: 'haskell-nested-comment', path: 'a.hs', source: '{- a {- b -} } -}\nx = "a } b"\n-- }\n' },
    { name: 'haskell-string-gap', path: 'a.hs', source: 'x = "a \\\n  \\ b } c"\n' },
    { name: 'haskell-prime-after-identifier', path: 'a.hs', source: "add' x = 1\n" },
    { name: 'haskell-char-literal', path: 'a.hs', source: "c = 'a'\n" },
    { name: 'yaml-quoted-hash', path: 'a.yaml', source: "# a comment\nkey: 'a # not a comment'\nother: \"b } c\"\n" },
    { name: 'toml-triple-quoted', path: 'a.toml', source: 'a = """x } y"""\nb = \'\'\'z }\'\'\'\n# c\n' },
    { name: 'ini-comments', path: 'a.ini', source: '; a comment\n# another } comment\nkey = value\n' },
    { name: 'default-unknown-type', path: null, source: '// a } brace\n/* b */\n"c } d"\n\'e }\'\n' },
    { name: 'default-no-extension', path: 'Makefile', source: '# comment }\n"a } b"\n' },
    { name: 'astral-plane-in-string', path: 'a.py', source: `x = "${EMOJI} } ${EMOJI}"\n${EMOJI} = 1\n` },
    { name: 'length-and-newlines-survive', path: 'a.java', source: 'int a;\r\n// c\r\nint b;\r\n' },
];

// ---------------------------------------------------------------------------
// The shape cases: the spellings a language adds to the generic heuristics.
//
// `line` is a *masked* line (it carries no comments or strings, so the mask is
// the line itself). Each row asserts every descriptor the language reports for
// it, in table order.
// ---------------------------------------------------------------------------

const shapeCases = [
    // --- Rust: `impl` scopes and `name: Type,` fields ----------------------
    { name: 'rust-impl-plain', path: 'a.rs', line: 'impl Cart {' },
    { name: 'rust-impl-generic', path: 'a.rs', line: 'impl<T: Clone> Display for Cart<T> {' },
    { name: 'rust-impl-nested-generic', path: 'a.rs', line: 'impl Foo<Bar<Baz>> {' },
    { name: 'rust-impl-where', path: 'a.rs', line: 'impl<T> Cart<T> where T: Clone {' },
    { name: 'rust-impl-word-containing-where', path: 'a.rs', line: 'impl where_clause for Cart {' },
    { name: 'rust-impl-body-on-next-line', path: 'a.rs', line: 'impl Cart' },
    { name: 'rust-field-plain', path: 'a.rs', line: '    field: u32,' },
    { name: 'rust-field-pub', path: 'a.rs', line: '    pub name: String,' },
    { name: 'rust-field-name-begins-with-pub', path: 'a.rs', line: '    publisher: String,' },
    { name: 'rust-field-name-is-pub-underscore', path: 'a.rs', line: '    pub_key: String,' },
    { name: 'rust-field-tuple-is-not-a-field', path: 'a.rs', line: '    (u32, u32),' },
    { name: 'rust-keyword-is-not-an-impl', path: 'a.rs', line: 'structure Cart {' },

    // --- Ruby: `def name`, parens optional, closed by `end` ----------------
    { name: 'ruby-def-plain', path: 'a.rb', line: 'def add' },
    { name: 'ruby-def-parens', path: 'a.rb', line: 'def add(x)' },
    { name: 'ruby-def-self', path: 'a.rb', line: 'def self.build' },
    { name: 'ruby-def-question', path: 'a.rb', line: 'def add?' },
    { name: 'ruby-def-bang', path: 'a.rb', line: 'def add!' },
    { name: 'ruby-def-setter', path: 'a.rb', line: 'def add=' },
    { name: 'ruby-def-indented', path: 'a.rb', line: '    def add' },
    { name: 'ruby-word-ending-in-def-is-not-a-def', path: 'a.rb', line: 'define add' },

    // --- Haskell: a binding and its `name ::` signature --------------------
    { name: 'haskell-binding-column-zero', path: 'a.hs', line: 'add x y = x + y' },
    { name: 'haskell-binding-indented', path: 'a.hs', line: '    add x y = x + y' },
    { name: 'haskell-binding-primed', path: 'a.hs', line: "add' x = 1" },
    { name: 'haskell-binding-named-fold', path: 'a.hs', line: "foldl' f z xs = z" },
    { name: 'haskell-binding-underscore', path: 'a.hs', line: '_ignore x = 1' },
    { name: 'haskell-equality-is-not-a-binding', path: 'a.hs', line: 'x == y' },
    { name: 'haskell-data', path: 'a.hs', line: 'data Cart = Cart { items :: [Int] }' },
    { name: 'haskell-newtype', path: 'a.hs', line: 'newtype Wrap a = Wrap a' },
    { name: 'haskell-type-primed', path: 'a.hs', line: "data Foo' = Foo" },
    { name: 'haskell-class-keyword', path: 'a.hs', line: 'class Store s where' },
    { name: 'haskell-indented-data', path: 'a.hs', line: '    data Bar = Bar' },
    { name: 'haskell-keyword-is-not-a-binding', path: 'a.hs', line: 'module Store where' },

    // --- VB: `Class`/`Module` and `Sub`/`Function` closed by `End …` -------
    { name: 'vb-class', path: 'a.vb', line: 'Public Class Form' },
    { name: 'vb-class-modifier-tight', path: 'a.vb', line: 'PublicClass Form' },
    { name: 'vb-class-not-inheritable', path: 'a.vb', line: 'Public NotInheritable Class Form' },
    { name: 'vb-module', path: 'a.vb', line: 'Friend Module Helpers' },
    { name: 'vb-structure', path: 'a.vb', line: 'Structure Point' },
    { name: 'vb-class-name-starts-with-digit', path: 'a.vb', line: 'Class 2Thing' },
    { name: 'vb-function', path: 'a.vb', line: '    Public Function Add(ByVal x As Integer) As Integer' },
    { name: 'vb-sub', path: 'a.vb', line: '    Private Sub Run()' },
    { name: 'vb-keyword-inside-a-longer-word', path: 'a.vb', line: 'Submarine Function Add(x)' },
    { name: 'vb-prefix-word-is-not-a-boundary', path: 'a.vb', line: 'MySub Foo' },
    { name: 'vb-end-is-not-a-declaration', path: 'a.vb', line: 'End Function' },
];

// ---------------------------------------------------------------------------

const lexerName = (path) => (path === null ? null : (lexerFor(path)?.name ?? null));

function buildMask(c) {
    const lexer = c.path === null ? null : lexerFor(c.path);
    const masked = lexer ? lexer.mask(c.source) : defaultMask(c.source);
    return { name: c.name, path: c.path, lexer: lexerName(c.path), source: c.source, masked };
}

function buildShape(c) {
    const lexer = lexerFor(c.path);
    const declared = (lexer?.declarations ? lexer.declarations(c.line) : []).map((d) => ({
        kind: d.kind,
        name: d.name,
        headerFrom: d.headerFrom,
        body: d.body ?? null,
        end: d.end ?? null,
        line: !!d.line,
    }));
    return { name: c.name, path: c.path, line: c.line, declared };
}

/**
 * Deterministic: fixed case order, fixed key order, LF endings, trailing
 * newline — and one row per line, so a diff names the row that changed.
 */
function oneRowPerLine(rows, indent) {
    const body = rows.map((row) => `${indent}  ${JSON.stringify(row)}`).join(',\n');
    return `${indent}[\n${body}\n${indent}]`;
}

function serialise() {
    const masks = oneRowPerLine(maskCases.map(buildMask), '  ');
    const shapes = oneRowPerLine(shapeCases.map(buildShape), '  ');
    return `{\n  "masks": ${masks},\n  "shapes": ${shapes}\n}\n`;
}

const out = serialise();

if (process.argv.includes('--check')) {
    let committed;
    try {
        committed = readFileSync(OUT, 'utf8');
    } catch {
        console.error('test/vectors/lexical-vectors.json is missing; run: node tools/lexical-vectors.mjs');
        process.exit(1);
    }
    if (committed === out) {
        console.log('lexical-vectors: ok');
        process.exit(0);
    }
    const want = committed.replace(/\r\n/g, '\n').split('\n');
    const have = out.replace(/\r\n/g, '\n').split('\n');
    console.error('lexical-vectors drift: the file does not match the implementation.');
    const n = Math.max(want.length, have.length);
    for (let i = 0; i < n; i++) {
        if (want[i] !== have[i]) {
            console.error(`  line ${i + 1}:`);
            console.error(`    committed: ${JSON.stringify(want[i] ?? '')}`);
            console.error(`    expected:  ${JSON.stringify(have[i] ?? '')}`);
        }
    }
    process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${maskCases.length} mask and ${shapeCases.length} shape vectors to test/vectors/lexical-vectors.json`);
