#!/usr/bin/env node

/**
 * Golden vectors for the section-matching contract (plans/section-matching).
 *
 * The behaviour the contract pins (grammar §5–§9, resolution §6–§8, walk
 * order and warnings §11) is frozen here as data: one JSON file of cases
 * generated by running this repository's own implementation — through the same
 * per-type lexer `index.mjs` selects by file extension, so a `.zig` case is
 * masked by the Zig lexer and an unknown type by the built-in default engine.
 * A later port to another language can treat this file as its target.
 *
 *   node tools/section-vectors.mjs           write/update the vectors file
 *   node tools/section-vectors.mjs --check   compare; exit 1 and diff on drift
 *
 * `--check` is a build gate: it fails when the committed file and the current
 * implementation disagree, so drift is caught rather than discovered.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseReference, planSection } from '../lib/section.mjs';
import { lexerFor } from '../src/js/scanner/lexers.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'test', 'vectors', 'section-vectors.json');

// --- The case list, hard-coded and hand-reviewable, in fixed order. --------
// `input` is a repo-relative path; `reference` is the `#` fragment
// content (without the prefix). `mode: 'parse'` checks the parser only
// (grammar and canonicalisation); everything else runs the resolver.
const EXAMPLE = 'test/fixtures/Example.java';
const ANCHORS = 'test/fixtures/Anchors.java';
const TS = 'test/fixtures/example.ts';
const ZIG = 'test/fixtures/Nesting.zig';

const cases = [
    // Grammar — parse only: canonical form and (lack of) errors.
    ...[
        'add', 'add-', 'add+', 'add++', '-add', '+add', '++add',
        'Cart/Line/render', 'Cart/Line-', 'Cart/-Line', 'Cart/Line/-render',
    ].map((reference) => ({ name: `grammar:${reference}`, mode: 'parse', reference })),

    // Grammar errors — parse only: the thrown message.
    ...[
        ['', 'empty'], ['a/', 'trailing-slash'], ['/a', 'leading-slash'],
        ['a//b', 'double-slash'], ['a/+b', 'plus-mid'], ['a/-b/c', 'dash-mid'],
        ['Cart/-Line/render', 'dash-second-of-three'],
        ['a+++', 'three-plus'], ['a---', 'three-dash'], ['a--', 'two-dash'],
        ['a/b/c/d/e/f/g/h/i', 'nine-segments'],
    ].map(([reference, slug]) => ({ name: `grammar-error:${slug}`, mode: 'parse', reference })),

    // Warnings — parse only: the contradiction and the canonical form.
    ...['a++-', 'a-++', 'a+-', 'a-+'].map((reference) => ({ name: `warning:${reference}`, mode: 'parse', reference })),

    // Resolution — Example.java.
    { name: 'ex-tostring', input: EXAMPLE, reference: 'toString' },
    { name: 'ex-tostring-body', input: EXAMPLE, reference: 'toString-' },
    { name: 'ex-tostring-annotated', input: EXAMPLE, reference: 'toString+' },
    { name: 'ex-tostring-documented', input: EXAMPLE, reference: 'toString++' },
    { name: 'ex-dash-tostring', input: EXAMPLE, reference: '-toString' },
    { name: 'ex-line', input: EXAMPLE, reference: 'Line' },
    { name: 'ex-cart-line', input: EXAMPLE, reference: 'Cart/Line' },
    { name: 'ex-cart-tostring', input: EXAMPLE, reference: 'Cart/toString' },
    { name: 'ex-cart-line-render', input: EXAMPLE, reference: 'Cart/Line/render' },
    { name: 'ex-cart-line-render-body', input: EXAMPLE, reference: 'Cart/Line/render-' },
    { name: 'ex-cart-line-dash-render', input: EXAMPLE, reference: 'Cart/Line/-render' },
    { name: 'ex-cart-line-body', input: EXAMPLE, reference: 'Cart/Line-' },
    { name: 'ex-line-tostring-error', input: EXAMPLE, reference: 'Line/toString' },
    { name: 'ex-render-extra-error', input: EXAMPLE, reference: 'Cart/Line/render/extra' },

    // Resolution — Anchors.java (condition literals, anchors, walk order).
    { name: 'a-getusers-anchor', input: ANCHORS, reference: 'getUsers' },
    { name: 'a-getusers-anchor-body', input: ANCHORS, reference: 'getUsers-' },
    { name: 'a-dispatch-getusers', input: ANCHORS, reference: 'dispatch/getUsers' },
    { name: 'a-getorders-anchor', input: ANCHORS, reference: 'getOrders' },
    { name: 'a-dispatch-getorders', input: ANCHORS, reference: 'dispatch/getOrders' },
    { name: 'a-handler-anchor', input: ANCHORS, reference: 'handler/getUsers' },
    { name: 'a-handler-anchor-body', input: ANCHORS, reference: 'handler/getUsers-' },
    { name: 'a-other-anchor', input: ANCHORS, reference: 'other/getOrders' },
    { name: 'a-other-anchor-body', input: ANCHORS, reference: 'other/getOrders-' },
    { name: 'a-string-not-condition', input: ANCHORS, reference: 'commentFromString/getUsers' },
    { name: 'a-case-sensitive-miss', input: ANCHORS, reference: 'getusers' },

    // Resolution — example.ts (region directives).
    { name: 'ts-table-region', input: TS, reference: 'table' },
    { name: 'ts-table-ignores-modifier', input: TS, reference: 'table+' },
    { name: 'ts-config-region', input: TS, reference: 'config' },

    // Resolution — Nesting.zig (the per-type lexer hides a declaration a nested
    // block comment wraps; the built-in default mask, non-nesting, would leak it).
    { name: 'z-target-method', input: ZIG, reference: 'target' },
    { name: 'z-decoy-hidden-by-nested-comment', input: ZIG, reference: 'decoy' },

    // Walk order — the shallower sibling beats a deeper block that comes sooner:
    // handler's anchor (a member of the class scope) beats dispatch's condition.
    { name: 'walkorder-siblings-before-deeper', input: ANCHORS, reference: 'getUsers' },
];

function warningOf(ref) {
    if (!ref.warning) return null;
    return { kind: ref.warning.kind, kept: ref.warning.kept, dropped: ref.warning.dropped };
}

function buildCase(c) {
    if (c.mode === 'parse') {
        let error = null;
        let warning = null;
        try { warning = warningOf(parseReference(c.reference)); } catch (e) { error = e.message; }
        return { name: c.name, input: null, reference: c.reference, text: null, error, warning };
    }
    const source = readFileSync(join(ROOT, c.input), 'utf8');
    try {
        const plan = planSection(source, c.reference, lexerFor(c.input));
        return {
            name: c.name, input: c.input, reference: c.reference,
            text: plan.text, error: null, warning: warningOf(plan.reference),
        };
    } catch (e) {
        return {
            name: c.name, input: c.input, reference: c.reference,
            text: null, error: e.message, warning: null,
        };
    }
}

/** Deterministic: fixed case order, fixed key order, LF endings, trailing newline. */
function serialise() {
    const rows = cases.map(buildCase).map((c) => JSON.stringify(c));
    return '[\n' + rows.map((r) => '  ' + r).join(',\n') + '\n]\n';
}

const out = serialise();
if (process.argv.includes('--check')) {
    let committed;
    try {
        committed = readFileSync(OUT, 'utf8');
    } catch {
        console.error('test/vectors/section-vectors.json is missing; run: node tools/section-vectors.mjs');
        process.exit(1);
    }
    if (committed === out) {
        console.log('section-vectors: ok');
        process.exit(0);
    }
    const want = committed.replace(/\r\n/g, '\n').split('\n');
    const have = out.replace(/\r\n/g, '\n').split('\n');
    console.error('section-vectors drift: the file does not match the implementation.');
    const n = Math.max(want.length, have.length);
    for (let i = 0; i < n; i++) {
        if (want[i] !== have[i]) {
            console.error(`  line ${i + 1}:`);
            console.error(`    committed: ${JSON.stringify(want[i] ?? '')}`);
            console.error(`    expected:  ${JSON.stringify(have[i] ?? '')}`);
        }
    }
    process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${cases.length} section vectors to test/vectors/section-vectors.json`);
