#!/usr/bin/env node
// @ts-check

/**
 * Golden vectors for the section-matching contract (plans/section-matching).
 *
 * The behaviour the contract pins (grammar §5–§9, resolution §6–§8, walk
 * order and warnings §11) is frozen here as data: one JSON file of cases
 * generated by running this repository's own implementation — through the same
 * per-type lexer `index.mjs` selects by file extension, so a `.zig` case is
 * masked by the Zig lexer and an unknown type by the built-in default engine.
 * A later port to another language can treat this file as its target.
 *
 * A resolution row carries three answers, because a consumer needs all three:
 * `text` (what to inject), `startLine`/`endLine` (the 1-based inclusive span it
 * came from, which is where a host navigates) and `kind` (which matcher found
 * it — `region`, `declaration`, `property`, `condition` or `anchor`, which is
 * what lets a host say how it knew). Every row has the same keys, with `null`
 * where the answer does not apply.
 *
 *   node tools/section-vectors.mjs           write/update the vectors file
 *   node tools/section-vectors.mjs --check   compare; exit 1 and diff on drift
 *
 * `--check` is a build gate: it fails when the committed file and the current
 * implementation disagree, so drift is caught rather than discovered.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseReference, planSection } from '../lib/section.mjs';
import { lexerFor } from '../src/js/scanner/lexers.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'test', 'vectors', 'section-vectors.json');

// --- The case list, hard-coded and hand-reviewable, in fixed order. --------
// `input` is a repo-relative path; `reference` is the `#` fragment
// content (without the prefix). `mode: 'parse'` checks the parser only
// (grammar and canonicalisation); everything else runs the resolver.
const EXAMPLE = 'test/fixtures/Example.java';
const ANCHORS = 'test/fixtures/Anchors.java';
const TS = 'test/fixtures/example.ts';
const ZIG = 'test/fixtures/Nesting.zig';
const RUBY = 'test/fixtures/Cart.rb';
const HASKELL = 'test/fixtures/Store.hs';
const RUST = 'test/fixtures/Cart.rs';
const SHAPES = 'test/fixtures/Shapes.java';
// The hard spellings: the shapes a matcher only gets right if it mirrors the
// JavaScript regex character for character. The fixtures above use the plain
// spellings, so a port can pass every one of them while reading
// `publisher: String,` as the field `lisher` and finding nothing in
// `impl<T: Clone> Display for Cart<T> {`.
const GENERICS = 'test/fixtures/Generics.rs';
const PRIME = 'test/fixtures/Prime.hs';
const WIDGET = 'test/fixtures/Widget.cs';
const REPO = 'test/fixtures/Repo.kt';
const ORDERS = 'test/fixtures/Orders.sql';
const VB_FORM = 'test/fixtures/Form.vb';

const cases = [
    // Grammar — parse only: canonical form and (lack of) errors.
    ...[
        'add', 'add-', 'add+', 'add++', '-add', '+add', '++add',
        'Cart/Line/render', 'Cart/Line-', 'Cart/-Line', 'Cart/Line/-render',
    ].map((reference) => ({ name: `grammar:${reference}`, mode: 'parse', reference })),

    // Grammar errors — parse only: the thrown message.
    ...[
        ['', 'empty'], ['a/', 'trailing-slash'], ['/a', 'leading-slash'],
        ['a//b', 'double-slash'], ['a/+b', 'plus-mid'], ['a/-b/c', 'dash-mid'],
        ['Cart/-Line/render', 'dash-second-of-three'],
        ['a+++', 'three-plus'], ['a---', 'three-dash'], ['a--', 'two-dash'],
        ['a/b/c/d/e/f/g/h/i', 'nine-segments'],
    ].map(([reference, slug]) => ({ name: `grammar-error:${slug}`, mode: 'parse', reference })),

    // Warnings — parse only: the contradiction and the canonical form.
    ...['a++-', 'a-++', 'a+-', 'a-+'].map((reference) => ({ name: `warning:${reference}`, mode: 'parse', reference })),

    // Resolution — Example.java.
    { name: 'ex-tostring', input: EXAMPLE, reference: 'toString' },
    { name: 'ex-tostring-body', input: EXAMPLE, reference: 'toString-' },
    { name: 'ex-tostring-annotated', input: EXAMPLE, reference: 'toString+' },
    { name: 'ex-tostring-documented', input: EXAMPLE, reference: 'toString++' },
    { name: 'ex-dash-tostring', input: EXAMPLE, reference: '-toString' },
    { name: 'ex-line', input: EXAMPLE, reference: 'Line' },
    { name: 'ex-cart-line', input: EXAMPLE, reference: 'Cart/Line' },
    { name: 'ex-cart-tostring', input: EXAMPLE, reference: 'Cart/toString' },
    { name: 'ex-cart-line-render', input: EXAMPLE, reference: 'Cart/Line/render' },
    { name: 'ex-cart-line-render-body', input: EXAMPLE, reference: 'Cart/Line/render-' },
    { name: 'ex-cart-line-dash-render', input: EXAMPLE, reference: 'Cart/Line/-render' },
    { name: 'ex-cart-line-body', input: EXAMPLE, reference: 'Cart/Line-' },
    { name: 'ex-line-tostring-error', input: EXAMPLE, reference: 'Line/toString' },
    { name: 'ex-render-extra-error', input: EXAMPLE, reference: 'Cart/Line/render/extra' },

    // Resolution — Shapes.java: the shape layer itself, which the fixtures above
    // only touch incidentally. Every row here is chosen to *discriminate*: a port
    // whose declaration matcher is too eager, or whose span lands a line off,
    // answers differently — including the rows whose expected answer is an error,
    // because over-matching shows up as a resolution that should not exist.
    { name: 'shapes-property', input: SHAPES, reference: 'getUsers' },
    { name: 'shapes-property-body', input: SHAPES, reference: 'getUsers-' },
    { name: 'shapes-label', input: SHAPES, reference: 'label' },
    // A call is not a declaration: the first thing in `calls` resolves to nothing,
    // and the method it calls comes from its own line.
    { name: 'shapes-calls-add-miss', input: SHAPES, reference: 'calls/add' },
    { name: 'shapes-add', input: SHAPES, reference: 'add' },
    { name: 'shapes-add-body', input: SHAPES, reference: 'add-' },
    // The anchor is only the *first* thing in the braces.
    { name: 'shapes-anchored', input: SHAPES, reference: 'anchored/anchor' },
    { name: 'shapes-not-anchored-miss', input: SHAPES, reference: 'notAnchored/anchor' },
    { name: 'shapes-anchored-body', input: SHAPES, reference: 'anchored-' },
    // A body that opens on the line *after* the header.
    { name: 'shapes-next-line-brace', input: SHAPES, reference: 'nextLineBrace' },
    { name: 'shapes-next-line-brace-body', input: SHAPES, reference: 'nextLineBrace-' },
    // An arrow-assigned member is a declaration with an expression body.
    { name: 'shapes-arrow', input: SHAPES, reference: 'arrow' },
    { name: 'shapes-arrow-body', input: SHAPES, reference: 'arrow-' },
    // An `if` with no literal is not a condition.
    { name: 'shapes-chains-if-miss', input: SHAPES, reference: 'chains/chain' },
    { name: 'shapes-chains', input: SHAPES, reference: 'chains' },
    // A region directive is a span, and never a comment anchor.
    { name: 'shapes-region', input: SHAPES, reference: 'wiring' },
    { name: 'shapes-region-miss', input: SHAPES, reference: 'anchored/wiring' },
    { name: 'shapes-regioned', input: SHAPES, reference: 'regioned' },


    { name: 'a-getusers-anchor', input: ANCHORS, reference: 'getUsers' },
    { name: 'a-getusers-anchor-body', input: ANCHORS, reference: 'getUsers-' },
    { name: 'a-dispatch-getusers', input: ANCHORS, reference: 'dispatch/getUsers' },
    { name: 'a-getorders-anchor', input: ANCHORS, reference: 'getOrders' },
    { name: 'a-dispatch-getorders', input: ANCHORS, reference: 'dispatch/getOrders' },
    { name: 'a-handler-anchor', input: ANCHORS, reference: 'handler/getUsers' },
    { name: 'a-handler-anchor-body', input: ANCHORS, reference: 'handler/getUsers-' },
    { name: 'a-other-anchor', input: ANCHORS, reference: 'other/getOrders' },
    { name: 'a-other-anchor-body', input: ANCHORS, reference: 'other/getOrders-' },
    { name: 'a-string-not-condition', input: ANCHORS, reference: 'commentFromString/getUsers' },
    { name: 'a-case-sensitive-miss', input: ANCHORS, reference: 'getusers' },

    // Resolution — example.ts (region directives).
    { name: 'ts-table-region', input: TS, reference: 'table' },
    { name: 'ts-table-ignores-modifier', input: TS, reference: 'table+' },
    { name: 'ts-config-region', input: TS, reference: 'config' },

    // Resolution — Nesting.zig (the per-type lexer hides a declaration a nested
    // block comment wraps; the built-in default mask, non-nesting, would leak it).
    { name: 'z-target-method', input: ZIG, reference: 'target' },
    { name: 'z-decoy-hidden-by-nested-comment', input: ZIG, reference: 'decoy' },

    // Walk order — the shallower sibling beats a deeper block that comes sooner:
    // handler's anchor (a member of the class scope) beats dispatch's condition.
    { name: 'walkorder-siblings-before-deeper', input: ANCHORS, reference: 'getUsers' },

    // Resolution — Cart.rb (a language that declares members with `def`, no
    // parentheses, and closes them with `end`).
    { name: 'rb-add', input: RUBY, reference: 'add' },
    { name: 'rb-cart-add', input: RUBY, reference: 'Cart/add' },
    { name: 'rb-cart-add-body', input: RUBY, reference: 'Cart/add-' },
    { name: 'rb-build', input: RUBY, reference: 'build' },
    { name: 'rb-missing', input: RUBY, reference: 'missing' },

    // Resolution — Store.hs (a binding and its `name ::` signature, a record).
    { name: 'hs-add', input: HASKELL, reference: 'add' },
    { name: 'hs-add-annotated', input: HASKELL, reference: 'add+' },
    { name: 'hs-add-body', input: HASKELL, reference: 'add-' },
    { name: 'hs-cart', input: HASKELL, reference: 'Cart' },
    { name: 'hs-keyword-is-not-a-member', input: HASKELL, reference: 'data' },

    // Resolution — Cart.rs (the path retries same-named scopes: the `struct` and
    // its `impl` blocks share the name `Cart`, so `Cart/add` has to pass over the
    // struct and the first impl to reach the second one's `remove`).
    { name: 'rs-struct-is-the-first-cart', input: RUST, reference: 'Cart' },
    { name: 'rs-impl-method', input: RUST, reference: 'Cart/add' },
    { name: 'rs-field-of-the-struct', input: RUST, reference: 'Cart/items' },
    { name: 'rs-retry-past-the-first-impl', input: RUST, reference: 'Cart/remove' },
    { name: 'rs-missing-in-every-cart', input: RUST, reference: 'Cart/nope' },

    // Resolution — the hard spellings, one fixture per shape that a matcher can
    // mistranslate. Every row here answers differently for a port whose matcher
    // is even slightly off, which is exactly what the plain fixtures cannot do.

    // Generics.rs: a generic impl, fields whose names begin with `pub`, and a
    // field type that is itself generic. A port that keeps the `pub` prefix, or
    // that reads `publisher` as `lisher`, or that cannot name the scope in
    // `impl<T: Clone> Display for Cart<T>`, fails at least one of these.
    { name: 'gneric-struct-is-the-first-cart', input: GENERICS, reference: 'Cart' },
    { name: 'generic-field-plain', input: GENERICS, reference: 'items' },
    { name: 'generic-field-in-scope', input: GENERICS, reference: 'Cart/items' },
    { name: 'generic-field-name-begins-with-pub', input: GENERICS, reference: 'publisher' },
    { name: 'generic-field-name-is-pub-underscore', input: GENERICS, reference: 'pub_key' },
    { name: 'generic-impl-method', input: GENERICS, reference: 'render' },
    { name: 'generic-impl-method-in-scope', input: GENERICS, reference: 'Cart/render' },
    { name: 'generic-plain-impl-method', input: GENERICS, reference: 'Cart/add' },
    // The impl's *type* names the scope, so its trait does not.
    { name: 'generic-trait-is-not-the-scope', input: GENERICS, reference: 'Display' },

    // Prime.hs: a binding whose source name carries a prime. The Haskell `'`
    // opens a char literal, so the masker blanks the rest of the line and the
    // binding is invisible — which is why `#add` misses while `#double` resolves.
    // A port that masks `'` differently answers these the other way round.
    { name: 'hs-primed-name-is-masked-away', input: PRIME, reference: 'add' },
    { name: 'hs-primed-name-is-not-a-section', input: PRIME, reference: "add'" },
    { name: 'hs-binding-with-where-clause', input: PRIME, reference: 'double' },
    // An indented `where` binding is not a top-level one.
    { name: 'hs-indented-where-binding-is-invisible', input: PRIME, reference: 'go' },
    { name: 'hs-primed-type-name-is-not-a-section', input: PRIME, reference: 'Foo' },
    { name: 'hs-class-with-a-primed-neighbour', input: PRIME, reference: 'Store' },
    { name: 'hs-indented-class-method-is-invisible', input: PRIME, reference: 'get' },
    { name: 'hs-keyword-is-not-a-binding', input: PRIME, reference: 'data' },

    // Widget.cs and Repo.kt: the two most-used languages after JavaScript had no
    // resolution vector at all, so their lexer entries were held only by their
    // own unit tests.
    { name: 'cs-class', input: WIDGET, reference: 'Widget' },
    { name: 'cs-method-in-scope', input: WIDGET, reference: 'Widget/Add' },
    { name: 'cs-method', input: WIDGET, reference: 'Add' },
    { name: 'cs-auto-property-is-not-a-section', input: WIDGET, reference: 'Name' },
    { name: 'kt-class', input: REPO, reference: 'Repo' },
    { name: 'kt-method-in-scope', input: REPO, reference: 'Repo/find' },
    { name: 'kt-method', input: REPO, reference: 'find' },
    { name: 'kt-second-method-in-scope', input: REPO, reference: 'Repo/save' },
    { name: 'kt-report-is-not-a-section', input: REPO, reference: 'report' },

    // Orders.sql: the SQL entry had no resolution vector either. A region in
    // `--` comments is the shape it exists for; `CREATE TABLE` is not a member.
    { name: 'sql-region-in-line-comments', input: ORDERS, reference: 'totals' },
    { name: 'sql-table-is-not-a-section', input: ORDERS, reference: 'orders' },

    // Form.vb: the VB entry, with its `End`-terminated bodies and its modifier
    // spellings (`Public Class`, `Private Sub`).
    { name: 'vb-class', input: VB_FORM, reference: 'Form' },
    { name: 'vb-function-in-scope', input: VB_FORM, reference: 'Form/Add' },
    { name: 'vb-function', input: VB_FORM, reference: 'Add' },
    { name: 'vb-function-body', input: VB_FORM, reference: 'Form/Add-' },
    { name: 'vb-sub-in-scope', input: VB_FORM, reference: 'Form/Run' },
    { name: 'vb-missing-member', input: VB_FORM, reference: 'Form/nope' },
];

function warningOf(ref) {
    if (!ref.warning) return null;
    return { kind: ref.warning.kind, kept: ref.warning.kept, dropped: ref.warning.dropped };
}

function buildCase(c) {
    if (c.mode === 'parse') {
        let error = null;
        let warning = null;
        try { warning = warningOf(parseReference(c.reference)); } catch (e) { error = e.message; }
        return {
            name: c.name, input: null, reference: c.reference, text: null,
            startLine: null, endLine: null, kind: null, error, warning,
        };
    }
    const source = readFileSync(join(ROOT, c.input), 'utf8');
    try {
        const plan = planSection(source, c.reference, lexerFor(c.input));
        return {
            name: c.name, input: c.input, reference: c.reference, text: plan.text,
            startLine: plan.startLine, endLine: plan.endLine, kind: plan.kind,
            error: null, warning: warningOf(plan.reference),
        };
    } catch (e) {
        return {
            name: c.name, input: c.input, reference: c.reference, text: null,
            startLine: null, endLine: null, kind: null, error: e.message, warning: null,
        };
    }
}

/** Deterministic: fixed case order, fixed key order, LF endings, trailing newline. */
function serialise() {
    const rows = cases.map(buildCase).map((c) => JSON.stringify(c));
    return '[\n' + rows.map((r) => '  ' + r).join(',\n') + '\n]\n';
}

const out = serialise();
if (process.argv.includes('--check')) {
    let committed;
    try {
        committed = readFileSync(OUT, 'utf8');
    } catch {
        console.error('test/vectors/section-vectors.json is missing; run: node tools/section-vectors.mjs');
        process.exit(1);
    }
    if (committed === out) {
        console.log('section-vectors: ok');
        process.exit(0);
    }
    const want = committed.replace(/\r\n/g, '\n').split('\n');
    const have = out.replace(/\r\n/g, '\n').split('\n');
    console.error('section-vectors drift: the file does not match the implementation.');
    const n = Math.max(want.length, have.length);
    for (let i = 0; i < n; i++) {
        if (want[i] !== have[i]) {
            console.error(`  line ${i + 1}:`);
            console.error(`    committed: ${JSON.stringify(want[i] ?? '')}`);
            console.error(`    expected:  ${JSON.stringify(have[i] ?? '')}`);
        }
    }
    process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${cases.length} section vectors to test/vectors/section-vectors.json`);
